language: python

python:
        - 2.7
        - 3.5

before_install:
        - sudo apt-get -qq update
        - sudo apt-get install -y numactl

install: 
        - pip install --upgrade pip
        - pip install -r requirements.txt
        - pip install -e .

script:
        - python -m pytest
